routingRules:
  rulesEngineEnabled: ROUTING_RULES_ENABLED
  rulesConfigPath: ROUTING_RULES_CONFIG_PATH

requestRouter:
  port: REQUEST_PORT
  name: trinoRouter
  historySize: QUERY_HISTORY_SIZE
  ssl: TLS_ENABLED
  keystorePath: KEYSTORE_PATH
  keystorePass: KEYSTORE_PASSWORD

extraWhitelistPaths:
  - "/ui/insights"
  - "/api/v1/biac"
  - "/api/v1/dataProduct"
  - "/api/v1/dataproduct"
  - "/ext/faster"
#TODO: Add Galaxy, BIAC and DP APIs

cookiePaths:
  - "/ui/insights/login/proceed"
  - "/oauth2/callback"

logoutCookiePaths:
  - "/ui/insights/logout"
  - "/ui/api/insights/logout"

clusterStatsConfiguration:
  useApi: false

#Healthcheck credentials
backendState:
  username: BACKEND_STATE_USERNAME
  password: BACKEND_STATE_PASSWORD
  ssl: BACKEND_STATE_SSL

dataStore:
  jdbcUrl: JDBC_URL
  user: DB_USER
  password: DB_PASSWORD
  driver: JDBC_DRIVER

server:
  applicationConnectors:
    - type: http
      port: APP_PORT
  adminConnectors:
    - type: http
      port: ADMIN_PORT

# This can be adjusted based on the coordinator state
monitor:
  connectionTimeout: HEALTHCHECK_CONNECTION_TIMEOUT
  #useJwtAuth: HEALTHCHECK_USE_JWT
  #jwt: "JWT_TOKEN"
  #jdbcPort: HEALTHCHECK_JDBC_PORT
  #jdbcUseSsl: HEALTHCHECK_JDBC_USE_SSL

notifier:
  recipients: []
  sender: 'foo@foobar.co'
  smtpAuthEnabled: false
  startTlsEnabled: false

modules:
  - io.trino.gateway.ha.module.HaGatewayProviderModule
  - io.trino.gateway.ha.module.ClusterStateListenerModule
  - io.trino.gateway.ha.module.ClusterStatsMonitorModule

managedApps:
  - io.trino.gateway.ha.GatewayManagedApp
  - io.trino.gateway.ha.clustermonitor.ActiveClusterMonitor

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: LOG_LEVEL

  # Logger-specific levels.
  loggers:
    io.trino: DEBUG
    io.trino.gateway.ha.persistence.JdbcConnectionManager: DEBUG

  appenders:
    - type: console
    - type: file
      currentLogFilename: /gateway/logs/gateway.log
      archivedLogFilenamePattern: /gateway/logs/gateway-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 100MB
